### ISSUE TITLE
Setup mongodb and load datasets

### ISSUE THREAD

**Issue by richard-donbosco** [JosueCom/LAR-backend#9]
- nonsql mongodb 

- Script to download the 
- Install mongodb 
- Create a location for the file storage locally 
- Import json into the database collection 
  - CLI 
  - python 
 - 
 
TODO:  

- [ ]  run docker container mongodb 
- [x] install mongosh cli 
- [x] install mongo compass
- [x] Experiment with loading datasets with json 
- [x] Write a python script to load data to mongo
- [ ] write the DB script for CRUD command 
- [ ] Richard: Write a docker compose file for backend flask, frontend angular and mongodb

**Comment by richard-donbosco** [comment]
tutorial link mongodb

https://www.tutorialspoint.com/mongodb/mongodb_overview.htm

**Comment by richard-donbosco** [comment]
have a script to download the datasets locally 
- one script -> dataset --> /src/data
- loader.py --> dataset from /src/data -> mongodb 
- then work whatever

**Comment by richard-donbosco** [comment]
docker run --name mongodb -d -p 27017:27017 -v ~/github/LAR-backend/src/data/mongodb:/data/db  mongo

**Comment by JosueCom** [comment]
Datasets: 
- https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::hospitals/explore?location=32.774157%2C-96.771332%2C12.96

**Comment by richard-donbosco** [comment]
https://www.mongodb.com/compatibility/json-to-mongodb

**Comment by JosueCom** [comment]
Command to create anaconda environment: `conda env create --file=environment.yml `
